### ISSUE TITLE
Mica effect

### ISSUE THREAD

**Issue by gaetandezeiraud** [Extrimis/Win32-Acrylic-Effect#5]
An update with Mica effect?

**Comment by selastingeorge** [comment]
There is a good news now all desktop apps can support mica effect without winui. Remember the SetWindowCompositionAttribute() you can use it to support mica on windows 11 for win32 apps. Checkout this repo : https://github.com/Difegue/Mica-WPF-Sample

**Comment by gaetandezeiraud** [comment]
Yes I know for this solution. But undocumented (so not exist officially). And need `WS_EX_NOREDIRECTIONBITMAP`. So the GDI don't render at all (so no inputs). We speak of this solution here https://github.com/electron/electron/issues/29937 (for ElectronJS). 

And the UWP Community Discord recommend to use Composition (But I don't know very well how it is working).

**Comment by selastingeorge** [comment]
This sample is also using undocumented api, you can easily build acrylic and mica using composition, if you use composition you won't be able to render anything other than direct composition based things, I think you know about the airspace issue, the only way to bypass is to create a seperate window and render acrylic or mica into seperate window and sync bot window position on resize and dragging. I tried that it works well but the problem is that you will lose animations for window. And it's a lot of code to work on, I am trying to build a project on this, I think you can rebuild mica easily than acrylic. But rendering it with other window contents is difficult.

I have built a sample based on windows.ui.composition , if there is any way to recreate the window maximize,minimize and restore animation it will work perfectly with any technology either it is win32 or wpf

**Comment by gaetandezeiraud** [comment]
Thanks for your time and help!

**Comment by selastingeorge** [comment]
> Thanks for your time and help!

I will let you know once I finish the project

**Comment by gaetandezeiraud** [comment]
Here code example for mica https://gist.github.com/sylveon/95afbd8424e3c111782e665629000729

**Comment by selastingeorge** [comment]
Thank you, I will add it in my new project, i was also thinking to bring the MICA on to windows 10 too, Since i cannot use CanvasDevice from Win2d of Win UI, i need to use the dwm private function to obtain the desktop thumbnail and blur it when using windows 10. if win2d canvas device was supported i would have taken the wallpaper directly.

**Comment by kamenomi-dev** [comment]
Hello, is there still any progress here?

**Comment by selastingeorge** [comment]
Hi, I haven't worked on it yet. May be I'll try it some other time.
