### ISSUE TITLE
Unrelated question; thank you for your research!

### ISSUE THREAD

**Issue by SteffanDonal** [Extrimis/Win32-Acrylic-Effect#7]
Hey there!
I've frequently come back to this repo in my W11 deep-dive, as it's one of the few places online that gathers multiple different approaches and documents them clearly.
Thank you for your hard work.

I've got an unrelated question - you mention that you've been able to get the WPF SwapChain:
> [..] The truth is Currently i was only able to get the swapchain backbuffer from WPF

Well, that's something I would find extremely useful. It's my understanding that many devs out there need/want a GPU-backed replacement for WPF's `RenderTargetBitmap`. Despite the many different flavours of XAML-based UI frameworks that exist now, it's still apparently a rare feature. If you happen to have that code lying around, I would love to take it, polish and turn it into a library.

**Comment by selastingeorge** [comment]
Hi, sorry i don't have the old source code i have replaced my laptop so it's all gone. But i have got a code that is used in d3d11, it's not wpf, but the old code is similar to this one : https://github.com/eugen15/directx-present-hook

Here is a wpf version: https://github.com/LiamRiddell/WPF-D3D9-Hook

**Comment by PandaTeemo** [comment]
hi. just wanted to jump in and say kudos on this project.

i found its the only one that accomplishes 0 latency. despite your listed limitation:
- Realtime Acrylic not supported, which means the host window redraw acrylic only when it is activated so fallback color is used.
though it seems to only sometimes work... but thats something ill dig into later.

this is something i cant achieve with any of the newer MS libs - Windows.UI.Composition and winui3 which all lag a frame behind. they also appear to have more restrictions like tagging the source window with an orange border :|

so a question, did you happen to try other directcomposition effects such as blending? the API implies creating a blend effect and that it requires 2 source images. yet theres no API to specify them.
IDCompositionFilterEffect.SetInput only takes other effects for some reason.

**Comment by selastingeorge** [comment]
Thank you @PandaTeemo , I haven't tried blend effects before, but I think it is possible to take multiple inputs for the IDCompositionFilterEffect.SetInput, notice the function definition

```C++
HRESULT SetInput(
  [in]           UINT     index,
  [in, optional] IUnknown *input,
  [in]           UINT     flags
);
```

You can have multiple inputs by calling the SetInput() function multiple times, the index value indicates the input index, I think an example can give a better overview, check this out:

```C++
ComPtr<ID2D1Effect> blendEffect;
m_d2dContext->CreateEffect(CLSID_D2D1Blend, &blendEffect);

blendEffect->SetInput(0, bitmap);
blendEffect->SetInput(1, bitmapTwo);
blendEffect->SetValue(D2D1_BLEND_PROP_MODE, D2D1_BLEND_MODE_EXCLUSION);

m_d2dContext->BeginDraw();
m_d2dContext->DrawImage(blendEffect.Get());
m_d2dContext->EndDraw();
```

This is the D2D Code for creating blend effect, you can see there set input is called multiple times to set two different inputs. you can do the same for IDCompositionFilterEffect.

**Comment by selastingeorge** [comment]
And I think WinUI3 also provides better ways to create acrylic and mica effect, checkout this page:[DesktopAcrylicController ](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.composition.systembackdrops.desktopacryliccontroller?view=windows-app-sdk-1.1)

**Comment by PandaTeemo** [comment]
are you saying the [DC setinput](https://learn.microsoft.com/en-us/windows/win32/api/dcomp/nf-dcomp-idcompositionfiltereffect-setinput) will accept D2D object/bitmaps? :) otherwise it states its limited to other effects :(

and the WinUI3 example appears to be win11 only. would like to support win10 a bit longer :)
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/system-backdrop-controller

**Comment by selastingeorge** [comment]
DC setinput cannot accept D2D bitmaps directly, but it is possible to draw d2d bitmaps on to IDCompositionVisual which you can use with DComp effects. checkout the CreateFallbackVisual() function in this code, there I draw the fallback color into ID2D1Bitmap1 and renders it with the help of Dcomp. but it is not possible to modify Dcomp visual using D2D.

I just want to know, have you able to fix the Airspace issue, because all the things that you need to draw on the window needs to be rendered using dcomp, otherwise the blur effect will overlap the content.
