### ISSUE TITLE
Can we use this as .dll for winform?

### ISSUE THREAD

**Issue by ahmedtalaat327** [Extrimis/Win32-Acrylic-Effect#8]
I was wondering if you can make a .dll to by used as exten in winforms C# language?

**Comment by selastingeorge** [comment]
While it's possible to convert it into a DLL for use in WinForms, there's a catch. Any elements added in the WinForms application won't be visible because the Direct Composition layer will overlap them. if you search for [Airspace issue](https://adityaswami89.wordpress.com/2014/02/24/airspace-problem-wpf/)  you will understand.

**Comment by ahmedtalaat327** [comment]
the hwnd was the only thing you can share between two windows but implementing this to a controller ex. Panel is impossible! thanks for this BTW.
